import type {
  GraphBuildRequest,
  DiscoveryRun,
  PipelineStage,
  AgentFinding,
  DiscoveredPage,
  CrawledPage,
  RosterEntry,
  NormalizedPerson,
  IdentityCandidate,
  AlumniProfile,
  ReviewItem,
  TeamStats,
  DashboardSection,
} from './types'

// ─── Team Build Request ────────────────────────────────────────────────────────

export const graphBuildRequest: GraphBuildRequest = {
  id: 'gbr-001',
  teamName: 'Penn Men\'s Golf',
  schoolName: 'University of Pennsylvania',
  sport: 'Men\'s Golf',
  gender: 'Men',
  officialTeamWebsite: 'https://pennathletics.com/sports/mens-golf',
  submittedAt: '2025-05-08T10:32:00Z',
  status: 'complete',
}

// ─── Discovery Run ─────────────────────────────────────────────────────────────

export const discoveryRun: DiscoveryRun = {
  id: 'run-001',
  teamId: 'penn-mens-golf',
  startedAt: '2025-05-08T10:32:05Z',
  completedAt: '2025-05-08T10:34:47Z',
  pagesDiscovered: 41,
  rosterPagesClassified: 26,
  rosterEntriesExtracted: 213,
  uniquePeopleNormalized: 84,
  profileCandidatesFound: 58,
  highConfidenceProfiles: 31,
  reviewItems: 17,
  connectionHooksGenerated: 146,
}

// ─── Pipeline Stages ──────────────────────────────────────────────────────────

export const pipelineStages: PipelineStage[] = [
  {
    id: 'stage-1',
    order: 1,
    label: 'Website Validated',
    description: 'Official team website confirmed reachable and well-structured.',
    status: 'complete',
    metric: '1',
    metricLabel: 'seed URL confirmed',
    completedAt: '2025-05-08T10:32:08Z',
    durationMs: 3100,
  },
  {
    id: 'stage-2',
    order: 2,
    label: 'Team Pages Discovered',
    description: 'Sitemap and link crawl surfaced roster, history, news, and archive pages.',
    status: 'complete',
    metric: '41',
    metricLabel: 'pages discovered',
    completedAt: '2025-05-08T10:32:31Z',
    durationMs: 22800,
  },
  {
    id: 'stage-3',
    order: 3,
    label: 'Roster Pages Classified',
    description: 'Pages ranked by likelihood of containing roster entries.',
    status: 'complete',
    metric: '26',
    metricLabel: 'roster/history pages',
    completedAt: '2025-05-08T10:32:45Z',
    durationMs: 14200,
  },
  {
    id: 'stage-4',
    order: 4,
    label: 'Roster Entries Extracted',
    description: 'Names, class years, hometowns, and high schools pulled from structured page data.',
    status: 'complete',
    metric: '213',
    metricLabel: 'entries extracted',
    completedAt: '2025-05-08T10:33:12Z',
    durationMs: 27400,
  },
  {
    id: 'stage-5',
    order: 5,
    label: 'People Normalized',
    description: 'Duplicate entries resolved. Canonical alumni identities created across seasons.',
    status: 'complete',
    metric: '84',
    metricLabel: 'unique people',
    completedAt: '2025-05-08T10:33:38Z',
    durationMs: 26100,
  },
  {
    id: 'stage-6',
    order: 6,
    label: 'Profile Candidates Found',
    description: 'Public LinkedIn profiles, company bios, and news mentions cross-referenced.',
    status: 'complete',
    metric: '58',
    metricLabel: 'candidates surfaced',
    completedAt: '2025-05-08T10:34:09Z',
    durationMs: 30800,
  },
  {
    id: 'stage-7',
    order: 7,
    label: 'Identities Scored',
    description: 'Evidence weighed: name, graduation year, hometown, school overlap.',
    status: 'complete',
    metric: '31',
    metricLabel: 'high-confidence profiles',
    completedAt: '2025-05-08T10:34:22Z',
    durationMs: 13100,
  },
  {
    id: 'stage-8',
    order: 8,
    label: 'Connection Hooks Generated',
    description: 'Source-supported tie explanations written for each verified alumnus.',
    status: 'complete',
    metric: '146',
    metricLabel: 'hooks generated',
    completedAt: '2025-05-08T10:34:39Z',
    durationMs: 16700,
  },
  {
    id: 'stage-9',
    order: 9,
    label: 'Human Review Queued',
    description: 'Low-confidence or ambiguous matches flagged for manual review.',
    status: 'complete',
    metric: '17',
    metricLabel: 'items in queue',
    completedAt: '2025-05-08T10:34:43Z',
    durationMs: 4100,
  },
  {
    id: 'stage-10',
    order: 10,
    label: 'Alumni Graph Ready',
    description: 'Private alumni relationship graph built. Ready to explore.',
    status: 'complete',
    metric: '84',
    metricLabel: 'alumni mapped',
    completedAt: '2025-05-08T10:34:47Z',
    durationMs: 3600,
  },
]

// ─── Agent Finding Feed ────────────────────────────────────────────────────────

export const agentFindings: AgentFinding[] = [
  { id: 'af-1', timestamp: '10:32:08', type: 'page_found', summary: 'Seed website validated', detail: 'pennathletics.com/sports/mens-golf loaded cleanly', confidence: 'high' },
  { id: 'af-2', timestamp: '10:32:12', type: 'page_found', summary: 'Roster index discovered', url: '/sports/mens-golf/roster', confidence: 'high' },
  { id: 'af-3', timestamp: '10:32:15', type: 'page_found', summary: 'History/archive page found', url: '/sports/mens-golf/history', confidence: 'high' },
  { id: 'af-4', timestamp: '10:32:19', type: 'page_found', summary: '2024–25 roster page classified', url: '/sports/mens-golf/roster/2024-25', confidence: 'high' },
  { id: 'af-5', timestamp: '10:32:23', type: 'page_found', summary: '2023–24 roster page classified', url: '/sports/mens-golf/roster/2023-24', confidence: 'high' },
  { id: 'af-6', timestamp: '10:32:31', type: 'page_found', summary: '41 total pages indexed', detail: '26 classified as roster/history priority', confidence: 'high' },
  { id: 'af-7', timestamp: '10:32:48', type: 'entry_extracted', summary: '8 entries from 2024–25 roster', confidence: 'high' },
  { id: 'af-8', timestamp: '10:32:55', type: 'entry_extracted', summary: '9 entries from 2023–24 roster', confidence: 'high' },
  { id: 'af-9', timestamp: '10:33:04', type: 'entry_extracted', summary: '7 entries from 2022–23 roster', confidence: 'high' },
  { id: 'af-10', timestamp: '10:33:12', type: 'entry_extracted', summary: '213 total entries extracted across 26 pages', confidence: 'high' },
  { id: 'af-11', timestamp: '10:33:24', type: 'person_normalized', summary: 'William Hartley matched across 3 seasons (2011–14)', confidence: 'high' },
  { id: 'af-12', timestamp: '10:33:29', type: 'person_normalized', summary: 'Carter Brennan matched across 2 seasons (2015–17)', confidence: 'high' },
  { id: 'af-13', timestamp: '10:33:35', type: 'person_normalized', summary: 'J. Whitmore vs James Whitmore — unified as one person', confidence: 'medium' },
  { id: 'af-14', timestamp: '10:33:38', type: 'person_normalized', summary: '84 unique people normalized from 213 entries', confidence: 'high' },
  { id: 'af-15', timestamp: '10:33:51', type: 'candidate_found', summary: 'LinkedIn public profile found for W. Hartley', detail: 'MD Anderson — matched name, Penn, graduation year', confidence: 'high' },
  { id: 'af-16', timestamp: '10:33:58', type: 'candidate_found', summary: 'Company bio found for James Whitmore', detail: 'NovaCap Ventures — mentioned Penn Golf', confidence: 'high' },
  { id: 'af-17', timestamp: '10:34:05', type: 'candidate_found', summary: 'LinkedIn found for Alex Chen', detail: 'KKR — name + graduation year overlap', confidence: 'high' },
  { id: 'af-18', timestamp: '10:34:09', type: 'candidate_found', summary: '58 total profile candidates surfaced', confidence: 'high' },
  { id: 'af-19', timestamp: '10:34:16', type: 'candidate_found', summary: 'M. Webb — 2 candidates, different employers', detail: 'Flagged for review (common name risk)', confidence: 'low' },
  { id: 'af-20', timestamp: '10:34:22', type: 'candidate_found', summary: '31 high-confidence, 10 medium, 17 review queue', confidence: 'high' },
  { id: 'af-21', timestamp: '10:34:29', type: 'hook_generated', summary: '"Both played at Aronimink — talk shop about the course"', confidence: 'high' },
  { id: 'af-22', timestamp: '10:34:33', type: 'hook_generated', summary: '"Whitmore founded NovaCap — strong founder advice tie"', confidence: 'high' },
  { id: 'af-23', timestamp: '10:34:39', type: 'hook_generated', summary: '146 connection hooks generated across 84 alumni', confidence: 'high' },
  { id: 'af-24', timestamp: '10:34:43', type: 'review_queued', summary: '17 items need human review before graph promotion', confidence: 'medium' },
  { id: 'af-25', timestamp: '10:34:47', type: 'person_normalized', summary: 'Alumni graph ready — 84 people, 31 verified, 17 in review', confidence: 'high' },
]

// ─── Discovered Pages ──────────────────────────────────────────────────────────

export const discoveredPages: DiscoveredPage[] = [
  { id: 'dp-1', url: 'https://pennathletics.com/sports/mens-golf/roster', pageType: 'roster', confidence: 'high', priority: 'high', discovered: true },
  { id: 'dp-2', url: 'https://pennathletics.com/sports/mens-golf/roster/2024-25', pageType: 'roster', season: '2024–25', confidence: 'high', priority: 'high', discovered: true },
  { id: 'dp-3', url: 'https://pennathletics.com/sports/mens-golf/roster/2023-24', pageType: 'roster', season: '2023–24', confidence: 'high', priority: 'high', discovered: true },
  { id: 'dp-4', url: 'https://pennathletics.com/sports/mens-golf/roster/2022-23', pageType: 'roster', season: '2022–23', confidence: 'high', priority: 'high', discovered: true },
  { id: 'dp-5', url: 'https://pennathletics.com/sports/mens-golf/roster/2021-22', pageType: 'roster', season: '2021–22', confidence: 'high', priority: 'high', discovered: true },
  { id: 'dp-6', url: 'https://pennathletics.com/sports/mens-golf/roster/2020-21', pageType: 'roster', season: '2020–21', confidence: 'high', priority: 'high', discovered: true },
  { id: 'dp-7', url: 'https://pennathletics.com/sports/mens-golf/roster/2019-20', pageType: 'roster', season: '2019–20', confidence: 'high', priority: 'high', discovered: true },
  { id: 'dp-8', url: 'https://pennathletics.com/sports/mens-golf/roster/2018-19', pageType: 'roster', season: '2018–19', confidence: 'high', priority: 'high', discovered: true },
  { id: 'dp-9', url: 'https://pennathletics.com/sports/mens-golf/roster/2017-18', pageType: 'roster', season: '2017–18', confidence: 'high', priority: 'high', discovered: true },
  { id: 'dp-10', url: 'https://pennathletics.com/sports/mens-golf/roster/2016-17', pageType: 'roster', season: '2016–17', confidence: 'high', priority: 'high', discovered: true },
  { id: 'dp-11', url: 'https://pennathletics.com/sports/mens-golf/roster/2015-16', pageType: 'roster', season: '2015–16', confidence: 'high', priority: 'high', discovered: true },
  { id: 'dp-12', url: 'https://pennathletics.com/sports/mens-golf/roster/2014-15', pageType: 'roster', season: '2014–15', confidence: 'high', priority: 'medium', discovered: true },
  { id: 'dp-13', url: 'https://pennathletics.com/sports/mens-golf/roster/2013-14', pageType: 'roster', season: '2013–14', confidence: 'high', priority: 'medium', discovered: true },
  { id: 'dp-14', url: 'https://pennathletics.com/sports/mens-golf/roster/2012-13', pageType: 'roster', season: '2012–13', confidence: 'medium', priority: 'medium', discovered: true },
  { id: 'dp-15', url: 'https://pennathletics.com/sports/mens-golf/roster/2011-12', pageType: 'roster', season: '2011–12', confidence: 'medium', priority: 'medium', discovered: true },
  { id: 'dp-16', url: 'https://pennathletics.com/sports/mens-golf/history', pageType: 'history', confidence: 'high', priority: 'high', discovered: true },
  { id: 'dp-17', url: 'https://pennathletics.com/sports/mens-golf/schedule', pageType: 'schedule', confidence: 'high', priority: 'medium', discovered: true },
  { id: 'dp-18', url: 'https://pennathletics.com/sports/mens-golf/news', pageType: 'news', confidence: 'high', priority: 'medium', discovered: true },
  { id: 'dp-19', url: 'https://pennathletics.com/sports/mens-golf/news/2023-24', pageType: 'news', season: '2023–24', confidence: 'medium', priority: 'low', discovered: true },
  { id: 'dp-20', url: 'https://pennathletics.com/sports/mens-golf/results', pageType: 'results', confidence: 'high', priority: 'medium', discovered: true },
  { id: 'dp-21', url: 'https://pennathletics.com/sports/mens-golf/archives/2010-11', pageType: 'archive', season: '2010–11', confidence: 'medium', priority: 'low', discovered: true },
  { id: 'dp-22', url: 'https://pennathletics.com/sports/mens-golf/archives/2009-10', pageType: 'archive', season: '2009–10', confidence: 'medium', priority: 'low', discovered: true },
  { id: 'dp-23', url: 'https://pennathletics.com/sports/mens-golf/archives/2008-09', pageType: 'archive', season: '2008–09', confidence: 'low', priority: 'low', discovered: true },
  { id: 'dp-24', url: 'https://pennathletics.com/sports/mens-golf/bio/hartley', pageType: 'bio', confidence: 'high', priority: 'medium', discovered: true },
  { id: 'dp-25', url: 'https://pennathletics.com/sports/mens-golf/bio/chen', pageType: 'bio', confidence: 'high', priority: 'medium', discovered: true },
  { id: 'dp-26', url: 'https://pennathletics.com/sports/mens-golf/bio/whitmore', pageType: 'bio', confidence: 'high', priority: 'medium', discovered: true },
  { id: 'dp-27', url: 'https://almanac.upenn.edu/golf', pageType: 'alumni', confidence: 'medium', priority: 'medium', discovered: true },
  { id: 'dp-28', url: 'https://pennathletics.com/sports/mens-golf/bio/brennan', pageType: 'bio', confidence: 'high', priority: 'medium', discovered: true },
  { id: 'dp-29', url: 'https://pennathletics.com/sports/mens-golf/bio/webb', pageType: 'bio', confidence: 'high', priority: 'medium', discovered: true },
  { id: 'dp-30', url: 'https://ivyleague.com/sports/golf/men', pageType: 'results', confidence: 'medium', priority: 'low', discovered: true },
  { id: 'dp-31', url: 'https://pennathletics.com/sports/mens-golf/news/pentathlon-2024', pageType: 'news', season: '2024', confidence: 'low', priority: 'low', discovered: true },
  { id: 'dp-32', url: 'https://pennathletics.com/sports/mens-golf/bio/sullivan', pageType: 'bio', confidence: 'high', priority: 'low', discovered: true },
  { id: 'dp-33', url: 'https://pennathletics.com/sports/mens-golf/bio/townsend', pageType: 'bio', confidence: 'high', priority: 'low', discovered: true },
  { id: 'dp-34', url: 'https://pennathletics.com/sports/mens-golf/bio/patel', pageType: 'bio', confidence: 'high', priority: 'low', discovered: true },
  { id: 'dp-35', url: 'https://pennathletics.com/sports/mens-golf/roster/2010-11', pageType: 'roster', season: '2010–11', confidence: 'low', priority: 'low', discovered: true },
  { id: 'dp-36', url: 'https://pennathletics.com/sports/mens-golf/archives/2007-08', pageType: 'archive', season: '2007–08', confidence: 'low', priority: 'low', discovered: true },
  { id: 'dp-37', url: 'https://golfstat.com/team/penn', pageType: 'results', confidence: 'medium', priority: 'low', discovered: true },
  { id: 'dp-38', url: 'https://pennathletics.com/sports/mens-golf/news/ivy-championship-2023', pageType: 'news', season: '2023', confidence: 'low', priority: 'low', discovered: true },
  { id: 'dp-39', url: 'https://pennathletics.com/sports/mens-golf/news/ivy-championship-2022', pageType: 'news', season: '2022', confidence: 'low', priority: 'low', discovered: true },
  { id: 'dp-40', url: 'https://pennathletics.com/sports/mens-golf/archives/2006-07', pageType: 'archive', season: '2006–07', confidence: 'low', priority: 'low', discovered: true },
  { id: 'dp-41', url: 'https://pennathletics.com/sports/mens-golf/archives/2005-06', pageType: 'archive', season: '2005–06', confidence: 'low', priority: 'low', discovered: true },
]

// ─── Crawled Pages ─────────────────────────────────────────────────────────────

export const crawledPages: CrawledPage[] = [
  { id: 'cp-1', url: 'https://pennathletics.com/sports/mens-golf/roster/2024-25', status: 'success', title: 'Men\'s Golf 2024–25 Roster', extractionStatus: 'extracted', entriesFound: 8, crawledAt: '2025-05-08T10:32:51Z' },
  { id: 'cp-2', url: 'https://pennathletics.com/sports/mens-golf/roster/2023-24', status: 'success', title: 'Men\'s Golf 2023–24 Roster', extractionStatus: 'extracted', entriesFound: 9, crawledAt: '2025-05-08T10:32:53Z' },
  { id: 'cp-3', url: 'https://pennathletics.com/sports/mens-golf/roster/2022-23', status: 'success', title: 'Men\'s Golf 2022–23 Roster', extractionStatus: 'extracted', entriesFound: 7, crawledAt: '2025-05-08T10:32:56Z' },
  { id: 'cp-4', url: 'https://pennathletics.com/sports/mens-golf/roster/2021-22', status: 'success', title: 'Men\'s Golf 2021–22 Roster', extractionStatus: 'extracted', entriesFound: 8, crawledAt: '2025-05-08T10:32:59Z' },
  { id: 'cp-5', url: 'https://pennathletics.com/sports/mens-golf/roster/2020-21', status: 'success', title: 'Men\'s Golf 2020–21 Roster', extractionStatus: 'extracted', entriesFound: 9, crawledAt: '2025-05-08T10:33:02Z' },
  { id: 'cp-6', url: 'https://pennathletics.com/sports/mens-golf/roster/2019-20', status: 'success', title: 'Men\'s Golf 2019–20 Roster', extractionStatus: 'extracted', entriesFound: 8, crawledAt: '2025-05-08T10:33:05Z' },
  { id: 'cp-7', url: 'https://pennathletics.com/sports/mens-golf/roster/2018-19', status: 'success', title: 'Men\'s Golf 2018–19 Roster', extractionStatus: 'extracted', entriesFound: 9, crawledAt: '2025-05-08T10:33:07Z' },
  { id: 'cp-8', url: 'https://pennathletics.com/sports/mens-golf/roster/2017-18', status: 'success', title: 'Men\'s Golf 2017–18 Roster', extractionStatus: 'extracted', entriesFound: 8, crawledAt: '2025-05-08T10:33:10Z' },
  { id: 'cp-9', url: 'https://pennathletics.com/sports/mens-golf/roster/2016-17', status: 'success', title: 'Men\'s Golf 2016–17 Roster', extractionStatus: 'extracted', entriesFound: 9, crawledAt: '2025-05-08T10:33:13Z' },
  { id: 'cp-10', url: 'https://pennathletics.com/sports/mens-golf/roster/2015-16', status: 'success', title: 'Men\'s Golf 2015–16 Roster', extractionStatus: 'extracted', entriesFound: 8, crawledAt: '2025-05-08T10:33:16Z' },
  { id: 'cp-11', url: 'https://pennathletics.com/sports/mens-golf/roster/2014-15', status: 'success', title: 'Men\'s Golf 2014–15 Roster', extractionStatus: 'extracted', entriesFound: 9, crawledAt: '2025-05-08T10:33:19Z' },
  { id: 'cp-12', url: 'https://pennathletics.com/sports/mens-golf/roster/2013-14', status: 'success', title: 'Men\'s Golf 2013–14 Roster', extractionStatus: 'extracted', entriesFound: 8, crawledAt: '2025-05-08T10:33:22Z' },
  { id: 'cp-13', url: 'https://pennathletics.com/sports/mens-golf/roster/2012-13', status: 'success', title: 'Men\'s Golf 2012–13 Roster', extractionStatus: 'partial', entriesFound: 6, crawledAt: '2025-05-08T10:33:25Z' },
  { id: 'cp-14', url: 'https://pennathletics.com/sports/mens-golf/roster/2011-12', status: 'success', title: 'Men\'s Golf 2011–12 Roster', extractionStatus: 'partial', entriesFound: 5, crawledAt: '2025-05-08T10:33:28Z' },
  { id: 'cp-15', url: 'https://pennathletics.com/sports/mens-golf/history', status: 'success', title: 'Penn Men\'s Golf — Program History', extractionStatus: 'partial', entriesFound: 12, crawledAt: '2025-05-08T10:33:31Z' },
  { id: 'cp-16', url: 'https://pennathletics.com/sports/mens-golf/archives/2010-11', status: 'success', title: 'Men\'s Golf Archive 2010–11', extractionStatus: 'partial', entriesFound: 4, crawledAt: '2025-05-08T10:33:34Z' },
  { id: 'cp-17', url: 'https://pennathletics.com/sports/mens-golf/archives/2009-10', status: 'success', title: 'Men\'s Golf Archive 2009–10', extractionStatus: 'partial', entriesFound: 3, crawledAt: '2025-05-08T10:33:37Z' },
  { id: 'cp-18', url: 'https://pennathletics.com/sports/mens-golf/archives/2008-09', status: 'success', title: 'Men\'s Golf Archive 2008–09', extractionStatus: 'no_data', crawledAt: '2025-05-08T10:33:40Z' },
  { id: 'cp-19', url: 'https://golfstat.com/team/penn', status: 'success', title: 'Penn Quakers — GolfStat', extractionStatus: 'partial', entriesFound: 18, crawledAt: '2025-05-08T10:33:43Z' },
  { id: 'cp-20', url: 'https://ivyleague.com/sports/golf/men', status: 'success', title: 'Ivy League Men\'s Golf', extractionStatus: 'partial', entriesFound: 7, crawledAt: '2025-05-08T10:33:46Z' },
  { id: 'cp-21', url: 'https://almanac.upenn.edu/golf', status: 'error', extractionStatus: 'failed', crawledAt: '2025-05-08T10:33:49Z' },
  { id: 'cp-22', url: 'https://pennathletics.com/sports/mens-golf/news', status: 'success', title: 'Penn Men\'s Golf News', extractionStatus: 'no_data', crawledAt: '2025-05-08T10:33:52Z' },
  { id: 'cp-23', url: 'https://pennathletics.com/sports/mens-golf/bio/hartley', status: 'success', title: 'William Hartley — Penn Men\'s Golf', extractionStatus: 'extracted', entriesFound: 1, crawledAt: '2025-05-08T10:33:55Z' },
  { id: 'cp-24', url: 'https://pennathletics.com/sports/mens-golf/bio/chen', status: 'success', title: 'Alex Chen — Penn Men\'s Golf', extractionStatus: 'extracted', entriesFound: 1, crawledAt: '2025-05-08T10:33:58Z' },
  { id: 'cp-25', url: 'https://pennathletics.com/sports/mens-golf/bio/whitmore', status: 'success', title: 'James Whitmore — Penn Men\'s Golf', extractionStatus: 'extracted', entriesFound: 1, crawledAt: '2025-05-08T10:34:01Z' },
  { id: 'cp-26', url: 'https://pennathletics.com/sports/mens-golf/archives/2007-08', status: 'skipped', extractionStatus: 'failed', crawledAt: '2025-05-08T10:34:04Z' },
]

// ─── Roster Entries (sample) ───────────────────────────────────────────────────

export const rosterEntries: RosterEntry[] = [
  { id: 're-1', name: 'William Hartley', classLabel: 'Sr.', hometown: 'Greenwich, CT', highSchool: 'Brunswick School', season: '2013–14', sourceUrl: '/roster/2013-14', confidence: 'high' },
  { id: 're-2', name: 'William Hartley', classLabel: 'Jr.', hometown: 'Greenwich, CT', highSchool: 'Brunswick School', season: '2012–13', sourceUrl: '/roster/2012-13', confidence: 'high' },
  { id: 're-3', name: 'William Hartley', classLabel: 'So.', hometown: 'Greenwich, CT', season: '2011–12', sourceUrl: '/roster/2011-12', confidence: 'medium' },
  { id: 're-4', name: 'Carter Brennan', classLabel: 'Sr.', hometown: 'Winnetka, IL', highSchool: 'New Trier HS', season: '2016–17', sourceUrl: '/roster/2016-17', confidence: 'high' },
  { id: 're-5', name: 'Carter Brennan', classLabel: 'Jr.', hometown: 'Winnetka, IL', season: '2015–16', sourceUrl: '/roster/2015-16', confidence: 'high' },
  { id: 're-6', name: 'James Whitmore', classLabel: 'Sr.', hometown: 'Scottsdale, AZ', highSchool: 'Desert Mountain HS', season: '2018–19', sourceUrl: '/roster/2018-19', confidence: 'high' },
  { id: 're-7', name: 'J. Whitmore', classLabel: 'Jr.', hometown: 'Scottsdale, AZ', season: '2017–18', sourceUrl: '/roster/2017-18', confidence: 'medium' },
  { id: 're-8', name: 'Alex Chen', classLabel: 'Sr.', hometown: 'San Jose, CA', highSchool: 'Harker School', season: '2020–21', sourceUrl: '/roster/2020-21', confidence: 'high' },
  { id: 're-9', name: 'Alex Chen', classLabel: 'Jr.', hometown: 'San Jose, CA', season: '2019–20', sourceUrl: '/roster/2019-20', confidence: 'high' },
  { id: 're-10', name: 'Alex Chen', classLabel: 'So.', hometown: 'San Jose, CA', season: '2018–19', sourceUrl: '/roster/2018-19', confidence: 'high' },
  { id: 're-11', name: 'Marcus Webb', classLabel: 'Sr.', hometown: 'Atlanta, GA', highSchool: 'Lovett School', season: '2022–23', sourceUrl: '/roster/2022-23', confidence: 'high' },
  { id: 're-12', name: 'Derek Sullivan', classLabel: 'Sr.', hometown: 'Boston, MA', highSchool: 'Milton Academy', season: '2019–20', sourceUrl: '/roster/2019-20', confidence: 'high' },
  { id: 're-13', name: 'Ryan Townsend', classLabel: 'Sr.', hometown: 'Dallas, TX', highSchool: 'St. Marks School', season: '2021–22', sourceUrl: '/roster/2021-22', confidence: 'high' },
  { id: 're-14', name: 'Thomas Patel', classLabel: 'Sr.', hometown: 'Chicago, IL', highSchool: 'Latin School', season: '2017–18', sourceUrl: '/roster/2017-18', confidence: 'high' },
  { id: 're-15', name: 'Michael Okafor', classLabel: 'Sr.', hometown: 'Houston, TX', highSchool: 'St. John\'s School', season: '2015–16', sourceUrl: '/roster/2015-16', confidence: 'high' },
  { id: 're-16', name: 'Brian Larson', classLabel: 'Sr.', hometown: 'Minneapolis, MN', highSchool: 'Blake School', season: '2014–15', sourceUrl: '/roster/2014-15', confidence: 'high' },
  { id: 're-17', name: 'Noah Fischer', classLabel: 'Sr.', hometown: 'Denver, CO', highSchool: 'Kent Denver', season: '2023–24', sourceUrl: '/roster/2023-24', confidence: 'high' },
  { id: 're-18', name: 'Jack Ambrose', classLabel: 'Sr.', hometown: 'Nashville, TN', highSchool: 'Montgomery Bell Academy', season: '2022–23', sourceUrl: '/roster/2022-23', confidence: 'high' },
  { id: 're-19', name: 'Daniel Reyes', classLabel: 'Sr.', hometown: 'Miami, FL', highSchool: 'Ransom Everglades', season: '2021–22', sourceUrl: '/roster/2021-22', confidence: 'high' },
  { id: 're-20', name: 'Samuel Park', classLabel: 'Sr.', hometown: 'Seattle, WA', highSchool: 'Lakeside School', season: '2016–17', sourceUrl: '/roster/2016-17', confidence: 'high' },
]

// ─── Normalized People ─────────────────────────────────────────────────────────

export const normalizedPeople: NormalizedPerson[] = [
  { id: 'np-1', canonicalName: 'William Hartley', rosterYears: ['2011–12', '2012–13', '2013–14'], classEstimate: 'Class of 2014', sourceCount: 3, confidence: 'high', graduationYear: 2014 },
  { id: 'np-2', canonicalName: 'Carter Brennan', rosterYears: ['2015–16', '2016–17'], classEstimate: 'Class of 2017', sourceCount: 3, confidence: 'high', graduationYear: 2017 },
  { id: 'np-3', canonicalName: 'James Whitmore', rosterYears: ['2017–18', '2018–19'], classEstimate: 'Class of 2019', sourceCount: 2, confidence: 'medium', graduationYear: 2019 },
  { id: 'np-4', canonicalName: 'Alex Chen', rosterYears: ['2018–19', '2019–20', '2020–21'], classEstimate: 'Class of 2021', sourceCount: 4, confidence: 'high', graduationYear: 2021 },
  { id: 'np-5', canonicalName: 'Marcus Webb', rosterYears: ['2021–22', '2022–23'], classEstimate: 'Class of 2023', sourceCount: 2, confidence: 'high', graduationYear: 2023 },
  { id: 'np-6', canonicalName: 'Derek Sullivan', rosterYears: ['2018–19', '2019–20'], classEstimate: 'Class of 2020', sourceCount: 2, confidence: 'high', graduationYear: 2020 },
  { id: 'np-7', canonicalName: 'Ryan Townsend', rosterYears: ['2020–21', '2021–22'], classEstimate: 'Class of 2022', sourceCount: 2, confidence: 'high', graduationYear: 2022 },
  { id: 'np-8', canonicalName: 'Thomas Patel', rosterYears: ['2016–17', '2017–18'], classEstimate: 'Class of 2018', sourceCount: 2, confidence: 'high', graduationYear: 2018 },
  { id: 'np-9', canonicalName: 'Michael Okafor', rosterYears: ['2014–15', '2015–16'], classEstimate: 'Class of 2016', sourceCount: 2, confidence: 'high', graduationYear: 2016 },
  { id: 'np-10', canonicalName: 'Brian Larson', rosterYears: ['2013–14', '2014–15'], classEstimate: 'Class of 2015', sourceCount: 2, confidence: 'high', graduationYear: 2015 },
  { id: 'np-11', canonicalName: 'Noah Fischer', rosterYears: ['2022–23', '2023–24'], classEstimate: 'Class of 2024', sourceCount: 2, confidence: 'high', graduationYear: 2024 },
  { id: 'np-12', canonicalName: 'Jack Ambrose', rosterYears: ['2021–22', '2022–23'], classEstimate: 'Class of 2023', sourceCount: 2, confidence: 'high', graduationYear: 2023 },
  { id: 'np-13', canonicalName: 'Daniel Reyes', rosterYears: ['2020–21', '2021–22'], classEstimate: 'Class of 2022', sourceCount: 2, confidence: 'high', graduationYear: 2022 },
  { id: 'np-14', canonicalName: 'Samuel Park', rosterYears: ['2015–16', '2016–17'], classEstimate: 'Class of 2017', sourceCount: 2, confidence: 'high', graduationYear: 2017 },
  { id: 'np-15', canonicalName: 'Christopher Walsh', rosterYears: ['2012–13', '2013–14'], classEstimate: 'Class of 2014', sourceCount: 2, confidence: 'medium', graduationYear: 2014 },
]

// ─── Identity Candidates ───────────────────────────────────────────────────────

export const identityCandidates: IdentityCandidate[] = [
  { id: 'ic-1', personId: 'np-1', personName: 'William Hartley', candidateUrl: 'https://linkedin.com/in/william-hartley-finance', sourceType: 'linkedin_public', evidence: ['Name match', 'Penn graduation year overlap', 'Based in New York, NY', 'Greenwich, CT hometown listed'], confidence: 'high', status: 'approved' },
  { id: 'ic-2', personId: 'np-2', personName: 'Carter Brennan', candidateUrl: 'https://midatlanticorthopedics.com/team/brennan', sourceType: 'company_bio', evidence: ['Name match', 'University of Pennsylvania listed', '"Varsity golf" mentioned in bio', 'Class of 2017 consistent'], confidence: 'high', status: 'approved' },
  { id: 'ic-3', personId: 'np-3', personName: 'James Whitmore', candidateUrl: 'https://novacap.vc/team/whitmore', sourceType: 'company_bio', evidence: ['Name match', '"Penn Golf alum" mentioned', 'Wharton MBA listed', 'Class of 2019 consistent'], confidence: 'high', status: 'approved' },
  { id: 'ic-4', personId: 'np-4', personName: 'Alex Chen', candidateUrl: 'https://linkedin.com/in/alex-chen-pe', sourceType: 'linkedin_public', evidence: ['Name match', 'Penn undergrad listed', 'San Jose, CA hometown consistent', 'Finance career'], confidence: 'high', status: 'approved' },
  { id: 'ic-5', personId: 'np-5', personName: 'Marcus Webb', candidateUrl: 'https://linkedin.com/in/marcus-webb-golf', sourceType: 'linkedin_public', evidence: ['Name match', 'Penn mentioned', 'Class of 2023 consistent', 'Golf coach role'], confidence: 'medium', status: 'needs_review' },
  { id: 'ic-6', personId: 'np-5', personName: 'Marcus Webb', candidateUrl: 'https://linkedin.com/in/marcus-webb-nyc', sourceType: 'linkedin_public', evidence: ['Name match', 'Penn mentioned', 'Finance role'], confidence: 'medium', status: 'needs_review' },
  { id: 'ic-7', personId: 'np-6', personName: 'Derek Sullivan', candidateUrl: 'https://sullivanmcallister.com/attorneys/sullivan', sourceType: 'company_bio', evidence: ['Name match', 'University of Pennsylvania listed', 'Boston, MA consistent', 'Class of 2020'], confidence: 'high', status: 'approved' },
  { id: 'ic-8', personId: 'np-7', personName: 'Ryan Townsend', candidateUrl: 'https://linkedin.com/in/ryan-townsend-realestate', sourceType: 'linkedin_public', evidence: ['Name match', 'Penn listed', 'Dallas, TX origin consistent', 'Real estate career'], confidence: 'high', status: 'approved' },
  { id: 'ic-9', personId: 'np-8', personName: 'Thomas Patel', candidateUrl: 'https://bridgelab.io/team', sourceType: 'company_bio', evidence: ['Name match', '"Penn Golf" mentioned in bio', 'Chicago, IL origin', 'Co-founder role'], confidence: 'high', status: 'approved' },
  { id: 'ic-10', personId: 'np-9', personName: 'Michael Okafor', candidateUrl: 'https://linkedin.com/in/michael-okafor-ibd', sourceType: 'linkedin_public', evidence: ['Name match', 'Penn undergrad', 'Houston, TX origin consistent', 'Investment banking'], confidence: 'high', status: 'approved' },
]

// ─── Alumni Profiles ───────────────────────────────────────────────────────────

export const alumniProfiles: AlumniProfile[] = [
  {
    id: 'alumni-1',
    canonicalName: 'William Hartley',
    firstName: 'William',
    lastName: 'Hartley',
    pennGolfYears: ['2011–12', '2012–13', '2013–14'],
    classYear: 2014,
    graduationYear: 2014,
    currentRole: 'Managing Director',
    currentCompany: 'Meridian Capital Partners',
    industry: 'Private Equity',
    city: 'New York',
    state: 'NY',
    bio: 'Managing Director at Meridian Capital Partners focusing on growth equity investments in financial services and fintech. Former Penn Golf team captain.',
    relationshipModes: ['career_chat', 'play_golf', 'finance_advice', 'mentorship', 'warm_intro'],
    contactPaths: [
      { id: 'cp-1a', type: 'linkedin_public_url', label: 'LinkedIn', value: 'linkedin.com/in/william-hartley-finance', preferred: true, verified: true },
      { id: 'cp-1b', type: 'coach_intro', label: 'Coach Intro', preferred: false, verified: true },
    ],
    connectionHooks: [
      { id: 'ch-1a', category: 'play_golf', text: 'Both played at Aronimink — William grew up in Greenwich and knows the course well.', sourceSupported: true, sourceSummary: 'Hometown listed on Penn roster page' },
      { id: 'ch-1b', category: 'career_chat', text: 'William is now in growth equity at Meridian — strong tie if you\'re interested in finance or PE recruiting.', sourceSupported: true, sourceSummary: 'Public LinkedIn profile' },
      { id: 'ch-1c', category: 'mentorship', text: 'Team captain in 2013–14 — led the team through Ivy season. Knows what it takes.', sourceSupported: true, sourceSummary: 'Penn Athletics roster page' },
      { id: 'ch-1d', category: 'warm_intro', text: 'Has deep IB/PE network in New York — strong warm intro potential.', sourceSupported: true, sourceSummary: 'Public LinkedIn connections' },
    ],
    suggestedAsks: [
      { mode: 'career_chat', ask: 'Ask about the path from Penn Golf to private equity', context: 'William went directly into IB before PE — a common path for athletes' },
      { mode: 'play_golf', ask: 'Ask about getting on a course in the New York area', context: 'William plays regularly and is listed as open to golf rounds' },
      { mode: 'finance_advice', ask: 'Ask about PE recruiting timelines from Wharton', context: 'William can speak to both the Wharton track and non-Wharton paths' },
    ],
    sourceEvidence: [
      { id: 'se-1a', url: 'https://pennathletics.com/sports/mens-golf/roster/2013-14', sourceType: 'team_roster', title: 'Penn Men\'s Golf 2013–14 Roster', snippet: 'William Hartley — Sr. — Greenwich, CT — Brunswick School', retrievedAt: '2025-05-08' },
      { id: 'se-1b', url: 'https://linkedin.com/in/william-hartley-finance', sourceType: 'linkedin_public', title: 'William Hartley — LinkedIn', snippet: 'Managing Director, Meridian Capital Partners | Penn \'14 | Former Penn Golf', retrievedAt: '2025-05-08' },
    ],
    confidence: 'high',
    verificationStatus: 'verified',
    relationshipStatus: 'saved',
    whyThisTieMatters: 'William was team captain your senior year and a Greenwich golfer who knows the Aronimink circuit. He\'s now at a respected PE shop in New York — a rare combination of shared fairways and a strong finance network.',
    howAgentFoundThis: 'Matched across three Penn Athletics roster pages (2011–12, 2012–13, 2013–14). LinkedIn public profile independently confirmed Penn Golf, graduation year, and Greenwich hometown.',
    isOpenToGolf: true,
    isOpenToCareerChat: true,
    isOpenToMentorship: true,
  },
  {
    id: 'alumni-2',
    canonicalName: 'Carter Brennan',
    firstName: 'Carter',
    lastName: 'Brennan',
    pennGolfYears: ['2015–16', '2016–17'],
    classYear: 2017,
    graduationYear: 2017,
    currentRole: 'Orthopedic Surgeon',
    currentCompany: 'Mid-Atlantic Orthopedics',
    industry: 'Medicine',
    city: 'Philadelphia',
    state: 'PA',
    bio: 'Board-certified orthopedic surgeon with a subspecialty in sports medicine. Penn Med alum. Treats collegiate and professional athletes.',
    relationshipModes: ['play_golf', 'mentorship', 'grad_school_advice', 'team_events', 'host_dinner'],
    contactPaths: [
      { id: 'cp-2a', type: 'public_employer_bio', label: 'Practice Website', value: 'midatlanticorthopedics.com/team/brennan', preferred: true, verified: true },
      { id: 'cp-2b', type: 'teammate_intro', label: 'Teammate Intro', preferred: false, verified: true },
    ],
    connectionHooks: [
      { id: 'ch-2a', category: 'play_golf', text: 'Carter is still in Philly — easy to get on a local course with a former teammate.', sourceSupported: true, sourceSummary: 'Practice website lists Philadelphia location' },
      { id: 'ch-2b', category: 'mentorship', text: 'Carter went Penn undergrad → Penn Med → orthopedic surgery. Strong path if pre-med or health-adjacent.', sourceSupported: true, sourceSummary: 'Practice bio mentions Penn undergrad and med school' },
      { id: 'ch-2c', category: 'grad_school_advice', text: 'Navigated Penn Med admissions as a varsity golfer — uniquely positioned to advise on pre-med timing as an athlete.', sourceSupported: true, sourceSummary: 'Penn Athletics roster and practice bio cross-reference' },
    ],
    suggestedAsks: [
      { mode: 'play_golf', ask: 'Ask about getting on Aronimink or Merion while he\'s nearby', context: 'Carter grew up in Winnetka but is settled in Philly now' },
      { mode: 'grad_school_advice', ask: 'Ask about managing pre-med as a varsity athlete at Penn', context: 'Carter threaded this needle and can speak to it genuinely' },
      { mode: 'team_events', ask: 'Ask if he\'d be up for a Penn Golf alumni round in Philly', context: 'Carter is local and likely interested in alumni events' },
    ],
    sourceEvidence: [
      { id: 'se-2a', url: 'https://pennathletics.com/sports/mens-golf/roster/2016-17', sourceType: 'team_roster', title: 'Penn Men\'s Golf 2016–17 Roster', snippet: 'Carter Brennan — Sr. — Winnetka, IL — New Trier HS', retrievedAt: '2025-05-08' },
      { id: 'se-2b', url: 'https://midatlanticorthopedics.com/team/brennan', sourceType: 'company_bio', title: 'Carter Brennan, MD — Mid-Atlantic Orthopedics', snippet: 'University of Pennsylvania undergrad and Penn Medicine. Former varsity golf.', retrievedAt: '2025-05-08' },
    ],
    confidence: 'high',
    verificationStatus: 'verified',
    relationshipStatus: 'planning_to_contact',
    whyThisTieMatters: 'Carter is a Penn Golf alum who stayed in Philadelphia — rare and valuable. He\'s an orthopedic surgeon who treats athletes, and he navigated Penn Med as a varsity golfer. If you\'re pre-med, curious about medicine, or just want a round in Philly, this is a great tie.',
    howAgentFoundThis: 'Found on Penn Athletics roster pages for 2015–16 and 2016–17. Practice website bio independently confirmed Penn undergrad, Penn Med, and varsity golf participation.',
    isOpenToGolf: true,
    isOpenToCareerChat: false,
    isOpenToMentorship: true,
  },
  {
    id: 'alumni-3',
    canonicalName: 'James Whitmore',
    firstName: 'James',
    lastName: 'Whitmore',
    pennGolfYears: ['2017–18', '2018–19'],
    classYear: 2019,
    graduationYear: 2019,
    currentRole: 'General Partner',
    currentCompany: 'NovaCap Ventures',
    industry: 'Venture Capital',
    city: 'San Francisco',
    state: 'CA',
    bio: 'General Partner at NovaCap Ventures, a seed-stage fund focused on infrastructure software and developer tools. Penn Golf alum. Wharton MBA.',
    relationshipModes: ['career_chat', 'founder_advice', 'finance_advice', 'warm_intro', 'mentorship'],
    contactPaths: [
      { id: 'cp-3a', type: 'public_employer_bio', label: 'Firm Website', value: 'novacap.vc/team/whitmore', preferred: true, verified: true },
      { id: 'cp-3b', type: 'linkedin_public_url', label: 'LinkedIn', value: 'linkedin.com/in/james-whitmore-vc', preferred: false, verified: true },
    ],
    connectionHooks: [
      { id: 'ch-3a', category: 'founder_advice', text: 'James invested in 3 Wharton-founded startups in the last 18 months — strong founder advice for anyone building.', sourceSupported: true, sourceSummary: 'NovaCap portfolio listed on firm website' },
      { id: 'ch-3b', category: 'career_chat', text: 'Went from Penn Golf to Wharton MBA to VC in 6 years — can speak to every step of that path.', sourceSupported: true, sourceSummary: 'Firm bio mentions Wharton and Penn undergrad timeline' },
      { id: 'ch-3c', category: 'warm_intro', text: 'James explicitly mentions Penn Golf on his firm bio — likely responsive to Penn Golf cold outreach.', sourceSupported: true, sourceSummary: '"Penn Golf alum" listed on NovaCap bio' },
    ],
    suggestedAsks: [
      { mode: 'founder_advice', ask: 'Ask for 20 minutes to talk about what investors look for at pre-seed', context: 'James invests at seed — can speak to what gets a founder to a first check' },
      { mode: 'career_chat', ask: 'Ask about the Wharton MBA decision and timing', context: 'He did undergrad → 2 years IB → Wharton → VC. A common high-finance path.' },
      { mode: 'warm_intro', ask: 'Ask if he knows anyone on the operator side at a growth-stage startup', context: 'His portfolio includes companies that hire Penn undergrads' },
    ],
    sourceEvidence: [
      { id: 'se-3a', url: 'https://pennathletics.com/sports/mens-golf/roster/2018-19', sourceType: 'team_roster', title: 'Penn Men\'s Golf 2018–19 Roster', snippet: 'James Whitmore — Sr. — Scottsdale, AZ — Desert Mountain HS', retrievedAt: '2025-05-08' },
      { id: 'se-3b', url: 'https://novacap.vc/team/whitmore', sourceType: 'company_bio', title: 'James Whitmore — NovaCap Ventures', snippet: 'Penn Golf alum. Wharton MBA. Seed-stage investor in infrastructure and developer tools.', retrievedAt: '2025-05-08' },
    ],
    confidence: 'high',
    verificationStatus: 'verified',
    relationshipStatus: 'contacted',
    whyThisTieMatters: 'James is a Penn Golf alum who explicitly mentions it on his firm bio — he signals openness to the connection. Now a GP at a seed-stage fund, he can open doors on the VC side that most Penn networks can\'t. Scottsdale golfer, Wharton alum, investor.',
    howAgentFoundThis: 'Matched across Penn Athletics roster pages for 2017–18 and 2018–19 (noting the "J. Whitmore" abbreviation on one page). NovaCap Ventures public team page bio independently confirmed Penn Golf and graduation year.',
    isOpenToGolf: false,
    isOpenToCareerChat: true,
    isOpenToMentorship: true,
  },
  {
    id: 'alumni-4',
    canonicalName: 'Alex Chen',
    firstName: 'Alex',
    lastName: 'Chen',
    pennGolfYears: ['2018–19', '2019–20', '2020–21'],
    classYear: 2021,
    graduationYear: 2021,
    currentRole: 'Associate',
    currentCompany: 'KKR',
    industry: 'Private Equity',
    city: 'New York',
    state: 'NY',
    bio: 'Private equity associate at KKR focused on technology and media buyouts. Penn Wharton alum. San Jose native and avid golfer.',
    relationshipModes: ['career_chat', 'play_golf', 'finance_advice', 'mentorship'],
    contactPaths: [
      { id: 'cp-4a', type: 'linkedin_public_url', label: 'LinkedIn', value: 'linkedin.com/in/alex-chen-pe', preferred: true, verified: true },
      { id: 'cp-4b', type: 'coach_intro', label: 'Coach Intro', preferred: false, verified: true },
    ],
    connectionHooks: [
      { id: 'ch-4a', category: 'career_chat', text: 'Alex went Wharton → Goldman IB → KKR PE on a very clean track — one of the best finance paths in the Penn Golf network.', sourceSupported: true, sourceSummary: 'LinkedIn public profile' },
      { id: 'ch-4b', category: 'play_golf', text: 'Alex is an avid golfer who grew up playing in the Bay Area — knows Pebble, Spyglass, and Harding Park.', sourceSupported: true, sourceSummary: 'Hometown listed on Penn roster + LinkedIn bio' },
      { id: 'ch-4c', category: 'mentorship', text: 'Finished Penn Golf career just 4 years ago — close enough to remember recruiting timelines and what worked.', sourceSupported: true, sourceSummary: 'Penn Athletics roster pages' },
    ],
    suggestedAsks: [
      { mode: 'career_chat', ask: 'Ask about on-cycle PE recruiting and what made his application stand out', context: 'Alex went through the process recently and can speak to current cycles' },
      { mode: 'play_golf', ask: 'Ask about getting on a course in the Tri-State area when he\'s around', context: 'Alex is in New York and plays regularly' },
    ],
    sourceEvidence: [
      { id: 'se-4a', url: 'https://pennathletics.com/sports/mens-golf/roster/2020-21', sourceType: 'team_roster', title: 'Penn Men\'s Golf 2020–21 Roster', snippet: 'Alex Chen — Sr. — San Jose, CA — Harker School', retrievedAt: '2025-05-08' },
      { id: 'se-4b', url: 'https://linkedin.com/in/alex-chen-pe', sourceType: 'linkedin_public', title: 'Alex Chen — LinkedIn', snippet: 'Associate at KKR | Penn Wharton \'21 | Former Penn Golf', retrievedAt: '2025-05-08' },
    ],
    confidence: 'high',
    verificationStatus: 'verified',
    relationshipStatus: 'replied',
    whyThisTieMatters: 'Alex is one of the strongest career ties in the Penn Golf network — a 2021 grad now at KKR who went through PE recruiting recently. He\'s also a genuine golfer, a rare combination in the finance world.',
    howAgentFoundThis: 'Matched across three Penn Athletics roster pages. LinkedIn public profile confirmed Penn Wharton, graduation year, San Jose origin, and current KKR role.',
    isOpenToGolf: true,
    isOpenToCareerChat: true,
    isOpenToMentorship: true,
  },
  {
    id: 'alumni-5',
    canonicalName: 'Derek Sullivan',
    firstName: 'Derek',
    lastName: 'Sullivan',
    pennGolfYears: ['2018–19', '2019–20'],
    classYear: 2020,
    graduationYear: 2020,
    currentRole: 'Associate Attorney',
    currentCompany: 'Sullivan & McAllister LLP',
    industry: 'Law',
    city: 'Boston',
    state: 'MA',
    bio: 'Corporate attorney specializing in M&A and private equity transactions. Penn Law alum. Milton Academy golf team alum.',
    relationshipModes: ['career_chat', 'play_golf', 'grad_school_advice', 'mentorship'],
    contactPaths: [
      { id: 'cp-5a', type: 'public_employer_bio', label: 'Firm Directory', value: 'sullivanmcallister.com/attorneys/sullivan', preferred: true, verified: true },
    ],
    connectionHooks: [
      { id: 'ch-5a', category: 'grad_school_advice', text: 'Derek went Penn undergrad → Penn Law — can speak to JD admissions as a former athlete.', sourceSupported: true, sourceSummary: 'Law firm bio mentions Penn Law and Penn undergrad' },
      { id: 'ch-5b', category: 'career_chat', text: 'M&A attorney in Boston — valuable if you\'re interested in law, finance law, or the Boston market.', sourceSupported: true, sourceSummary: 'Public firm bio' },
      { id: 'ch-5c', category: 'play_golf', text: 'Grew up at The Country Club in Brookline — likely connected to the Boston golf scene.', sourceSupported: true, sourceSummary: 'Milton Academy mentioned on Penn roster' },
    ],
    suggestedAsks: [
      { mode: 'grad_school_advice', ask: 'Ask about the LSAT timeline as a varsity golfer and the Penn Law experience', context: 'Derek can speak directly to the Penn Law application process' },
    ],
    sourceEvidence: [
      { id: 'se-5a', url: 'https://pennathletics.com/sports/mens-golf/roster/2019-20', sourceType: 'team_roster', title: 'Penn Men\'s Golf 2019–20 Roster', snippet: 'Derek Sullivan — Sr. — Boston, MA — Milton Academy', retrievedAt: '2025-05-08' },
      { id: 'se-5b', url: 'https://sullivanmcallister.com/attorneys/sullivan', sourceType: 'company_bio', title: 'Derek Sullivan — Sullivan & McAllister', snippet: 'University of Pennsylvania (BA, JD). Corporate M&A and PE transactions.', retrievedAt: '2025-05-08' },
    ],
    confidence: 'high',
    verificationStatus: 'verified',
    whyThisTieMatters: 'Derek is a Penn Golf → Penn Law alum now doing corporate M&A in Boston. A rare athlete-lawyer profile who can advise on law school, the Boston legal market, and the Milton golf scene.',
    howAgentFoundThis: 'Found on Penn Athletics roster pages for 2018–19 and 2019–20. Sullivan & McAllister LLP public attorney directory confirmed Penn undergrad and Penn Law.',
    isOpenToGolf: true,
    isOpenToCareerChat: true,
    isOpenToMentorship: true,
  },
  {
    id: 'alumni-6',
    canonicalName: 'Ryan Townsend',
    firstName: 'Ryan',
    lastName: 'Townsend',
    pennGolfYears: ['2020–21', '2021–22'],
    classYear: 2022,
    graduationYear: 2022,
    currentRole: 'Associate, Acquisitions',
    currentCompany: 'Crescent Real Estate',
    industry: 'Real Estate',
    city: 'Dallas',
    state: 'TX',
    bio: 'Real estate acquisitions associate at Crescent covering Texas and Sun Belt markets. Penn grad. St. Mark\'s School golf alum.',
    relationshipModes: ['career_chat', 'play_golf', 'city_advice', 'mentorship'],
    contactPaths: [
      { id: 'cp-6a', type: 'linkedin_public_url', label: 'LinkedIn', value: 'linkedin.com/in/ryan-townsend-realestate', preferred: true, verified: true },
    ],
    connectionHooks: [
      { id: 'ch-6a', category: 'play_golf', text: 'Ryan grew up playing Colonial Country Club in Dallas — knows the Texas golf scene deeply.', sourceSupported: true, sourceSummary: 'St. Mark\'s School listed on Penn roster' },
      { id: 'ch-6b', category: 'city_advice', text: 'Ryan is based in Dallas and knows the market well — great for advice on Dallas/Fort Worth life and real estate.', sourceSupported: true, sourceSummary: 'LinkedIn public profile' },
      { id: 'ch-6c', category: 'career_chat', text: 'Real estate acquisitions is a target for athlete hires — Ryan can speak to the path from Penn to CRE.', sourceSupported: true, sourceSummary: 'LinkedIn public profile' },
    ],
    suggestedAsks: [
      { mode: 'city_advice', ask: 'Ask about what Dallas is actually like to live in post-graduation', context: 'Ryan moved back to Texas after Penn and knows the city from a 20-something perspective' },
      { mode: 'play_golf', ask: 'Ask about getting a round in if you\'re ever in Dallas', context: 'Ryan has connections at several private clubs in the DFW area' },
    ],
    sourceEvidence: [
      { id: 'se-6a', url: 'https://pennathletics.com/sports/mens-golf/roster/2021-22', sourceType: 'team_roster', title: 'Penn Men\'s Golf 2021–22 Roster', snippet: 'Ryan Townsend — Sr. — Dallas, TX — St. Mark\'s School', retrievedAt: '2025-05-08' },
      { id: 'se-6b', url: 'https://linkedin.com/in/ryan-townsend-realestate', sourceType: 'linkedin_public', title: 'Ryan Townsend — LinkedIn', snippet: 'Associate at Crescent Real Estate | Penn \'22 | Dallas, TX', retrievedAt: '2025-05-08' },
    ],
    confidence: 'high',
    verificationStatus: 'verified',
    whyThisTieMatters: 'Ryan is a recent Penn Golf alum (class of \'22) back in Dallas doing real estate acquisitions. Texas golf, CRE career path, and city advice all in one connection.',
    howAgentFoundThis: 'Found on Penn Athletics roster pages for 2020–21 and 2021–22. LinkedIn public profile confirmed Penn, graduation year, Dallas location, and Crescent Real Estate role.',
    isOpenToGolf: true,
    isOpenToCareerChat: true,
    isOpenToMentorship: false,
  },
  {
    id: 'alumni-7',
    canonicalName: 'Thomas Patel',
    firstName: 'Thomas',
    lastName: 'Patel',
    pennGolfYears: ['2016–17', '2017–18'],
    classYear: 2018,
    graduationYear: 2018,
    currentRole: 'Co-Founder & CEO',
    currentCompany: 'Bridgelab',
    industry: 'Technology',
    city: 'Chicago',
    state: 'IL',
    bio: 'Co-founder and CEO of Bridgelab, a B2B SaaS platform for construction project management. Penn Engineering alum. Latin School golf alum.',
    relationshipModes: ['founder_advice', 'career_chat', 'mentorship', 'warm_intro', 'play_golf'],
    contactPaths: [
      { id: 'cp-7a', type: 'public_employer_bio', label: 'Company Website', value: 'bridgelab.io/team', preferred: true, verified: true },
      { id: 'cp-7b', type: 'linkedin_public_url', label: 'LinkedIn', preferred: false, verified: false },
    ],
    connectionHooks: [
      { id: 'ch-7a', category: 'founder_advice', text: 'Thomas is a founder who built from Penn — can speak to starting a company right out of undergrad vs. working first.', sourceSupported: true, sourceSummary: 'Bridgelab company website bio' },
      { id: 'ch-7b', category: 'career_chat', text: 'Bridgelab raised a Series A — Thomas has navigated fundraising, hiring, and product from zero.', sourceSupported: true, sourceSummary: 'Company press page (public)' },
      { id: 'ch-7c', category: 'play_golf', text: 'Chicago golfer who knows Shoreacres and Exmoor — if you\'re ever in Chicago, a round with a founder is hard to beat.', sourceSupported: true, sourceSummary: 'Latin School and Chicago hometown on Penn roster' },
    ],
    suggestedAsks: [
      { mode: 'founder_advice', ask: 'Ask what he wishes he\'d known before starting a company right out of school', context: 'Thomas started Bridgelab within a year of graduating — rare and direct experience' },
    ],
    sourceEvidence: [
      { id: 'se-7a', url: 'https://pennathletics.com/sports/mens-golf/roster/2017-18', sourceType: 'team_roster', title: 'Penn Men\'s Golf 2017–18 Roster', snippet: 'Thomas Patel — Sr. — Chicago, IL — Latin School', retrievedAt: '2025-05-08' },
      { id: 'se-7b', url: 'https://bridgelab.io/team', sourceType: 'company_bio', title: 'Thomas Patel — Bridgelab', snippet: 'Co-Founder & CEO. Penn Engineering \'18. Penn Golf alum.', retrievedAt: '2025-05-08' },
    ],
    confidence: 'high',
    verificationStatus: 'verified',
    whyThisTieMatters: 'Thomas is one of the few Penn Golf founders — building a B2B SaaS company in Chicago after an Engineering degree. Rare to find a former teammate who can speak to both starting a company and what the early-career tech path looks like.',
    howAgentFoundThis: 'Found on Penn Athletics roster pages for 2016–17 and 2017–18. Bridgelab public team page bio explicitly mentioned Penn Golf and Penn Engineering graduation year.',
    isOpenToGolf: true,
    isOpenToCareerChat: true,
    isOpenToMentorship: true,
  },
  {
    id: 'alumni-8',
    canonicalName: 'Michael Okafor',
    firstName: 'Michael',
    lastName: 'Okafor',
    pennGolfYears: ['2014–15', '2015–16'],
    classYear: 2016,
    graduationYear: 2016,
    currentRole: 'Vice President',
    currentCompany: 'Goldman Sachs',
    industry: 'Investment Banking',
    city: 'New York',
    state: 'NY',
    bio: 'Vice President in Goldman Sachs Natural Resources coverage. Penn alum. Houston native and lifelong golfer.',
    relationshipModes: ['career_chat', 'finance_advice', 'play_golf', 'mentorship', 'warm_intro'],
    contactPaths: [
      { id: 'cp-8a', type: 'linkedin_public_url', label: 'LinkedIn', value: 'linkedin.com/in/michael-okafor-ibd', preferred: true, verified: true },
      { id: 'cp-8b', type: 'coach_intro', label: 'Coach Intro', preferred: false, verified: true },
    ],
    connectionHooks: [
      { id: 'ch-8a', category: 'career_chat', text: 'Michael has been at Goldman since graduation — nearly a decade of IBD experience and knows every stage of the path.', sourceSupported: true, sourceSummary: 'LinkedIn public profile' },
      { id: 'ch-8b', category: 'finance_advice', text: 'Natural resources coverage at GS — uniquely valuable for anyone interested in energy, commodities, or impact investing.', sourceSupported: true, sourceSummary: 'LinkedIn public profile' },
      { id: 'ch-8c', category: 'play_golf', text: 'Houston golfer who grew up at River Oaks — has impeccable taste in courses and loves playing.', sourceSupported: true, sourceSummary: 'Hometown on Penn roster (Houston, TX — St. John\'s School)' },
    ],
    suggestedAsks: [
      { mode: 'career_chat', ask: 'Ask about the first-year analyst experience at Goldman and what separates the analysts who make VP', context: 'Michael has seen hundreds of analysts come through the door' },
      { mode: 'finance_advice', ask: 'Ask about energy and natural resources as a sector for early-career finance', context: 'Michael covers an underrated sector with a lot of Penn interest post-inflation' },
    ],
    sourceEvidence: [
      { id: 'se-8a', url: 'https://pennathletics.com/sports/mens-golf/roster/2015-16', sourceType: 'team_roster', title: 'Penn Men\'s Golf 2015–16 Roster', snippet: 'Michael Okafor — Sr. — Houston, TX — St. John\'s School', retrievedAt: '2025-05-08' },
      { id: 'se-8b', url: 'https://linkedin.com/in/michael-okafor-ibd', sourceType: 'linkedin_public', title: 'Michael Okafor — LinkedIn', snippet: 'VP at Goldman Sachs | Penn \'16 | Natural Resources Coverage', retrievedAt: '2025-05-08' },
    ],
    confidence: 'high',
    verificationStatus: 'verified',
    whyThisTieMatters: 'Michael is a career Goldman banker who has built a strong track record in natural resources. Houston golfer, Penn Golf alum, and one of the most tenured finance connections in the network.',
    howAgentFoundThis: 'Found on Penn Athletics roster pages for 2014–15 and 2015–16. LinkedIn public profile confirmed Penn, graduation year, Goldman Sachs, and Houston origin.',
    isOpenToGolf: true,
    isOpenToCareerChat: true,
    isOpenToMentorship: true,
  },
  {
    id: 'alumni-9',
    canonicalName: 'Noah Fischer',
    firstName: 'Noah',
    lastName: 'Fischer',
    pennGolfYears: ['2022–23', '2023–24'],
    classYear: 2024,
    graduationYear: 2024,
    currentRole: 'Analyst',
    currentCompany: 'Evercore',
    industry: 'Investment Banking',
    city: 'New York',
    state: 'NY',
    bio: 'First-year analyst at Evercore in the restructuring group. Recent Penn Golf alum. Denver native.',
    relationshipModes: ['career_chat', 'play_golf', 'mentorship', 'city_advice'],
    contactPaths: [
      { id: 'cp-9a', type: 'linkedin_public_url', label: 'LinkedIn', preferred: true, verified: true },
      { id: 'cp-9b', type: 'teammate_intro', label: 'Teammate Intro', preferred: false, verified: true },
    ],
    connectionHooks: [
      { id: 'ch-9a', category: 'career_chat', text: 'Noah just finished recruiting last cycle — most current person in the network to ask about the process.', sourceSupported: true, sourceSummary: 'Penn roster 2023–24 confirms recent grad timeline' },
      { id: 'ch-9b', category: 'play_golf', text: 'Denver golfer who played collegiate golf through the COVID era — shared experience of that disrupted season.', sourceSupported: true, sourceSummary: 'Penn Athletics roster 2022–23, 2023–24' },
      { id: 'ch-9c', category: 'city_advice', text: 'Just moved to New York — can give you the honest first-year-analyst perspective on the city.', sourceSupported: true, sourceSummary: 'LinkedIn public profile' },
    ],
    suggestedAsks: [
      { mode: 'career_chat', ask: 'Ask about the SA recruiting timeline and what Evercore\'s restructuring group looks for', context: 'Noah went through this very recently' },
      { mode: 'play_golf', ask: 'Ask about his favorite Denver courses and if he plays in New York', context: 'Kent Denver is an excellent golf program — good ice breaker' },
    ],
    sourceEvidence: [
      { id: 'se-9a', url: 'https://pennathletics.com/sports/mens-golf/roster/2023-24', sourceType: 'team_roster', title: 'Penn Men\'s Golf 2023–24 Roster', snippet: 'Noah Fischer — Sr. — Denver, CO — Kent Denver', retrievedAt: '2025-05-08' },
    ],
    confidence: 'high',
    verificationStatus: 'verified',
    whyThisTieMatters: 'Noah is the most recent Penn Golf alum in the banking network — graduated in 2024 and just finished the most current recruiting cycle. Perfect to call on for fresh recruiting intel, New York advice, and a shared COVID-era golf season.',
    howAgentFoundThis: 'Found on Penn Athletics roster pages for 2022–23 and 2023–24. LinkedIn profile confirmed Evercore analyst role and recent graduation.',
    isOpenToGolf: true,
    isOpenToCareerChat: true,
    isOpenToMentorship: false,
  },
  {
    id: 'alumni-10',
    canonicalName: 'Brian Larson',
    firstName: 'Brian',
    lastName: 'Larson',
    pennGolfYears: ['2013–14', '2014–15'],
    classYear: 2015,
    graduationYear: 2015,
    currentRole: 'Partner',
    currentCompany: 'McKinsey & Company',
    industry: 'Consulting',
    city: 'Chicago',
    state: 'IL',
    bio: 'Partner at McKinsey & Company in the industrial practice. Penn alum. Blake School (Minneapolis) golf alum. Covers operations and supply chain transformation.',
    relationshipModes: ['career_chat', 'mentorship', 'play_golf', 'grad_school_advice', 'warm_intro'],
    contactPaths: [
      { id: 'cp-10a', type: 'linkedin_public_url', label: 'LinkedIn', preferred: true, verified: true },
    ],
    connectionHooks: [
      { id: 'ch-10a', category: 'career_chat', text: 'Brian made Partner at McKinsey — can speak to the full consulting career arc from analyst to partner.', sourceSupported: true, sourceSummary: 'LinkedIn public profile' },
      { id: 'ch-10b', category: 'grad_school_advice', text: 'Did a McKinsey-sponsored MBA — can advise on the MBA decision timing and application while in consulting.', sourceSupported: true, sourceSummary: 'LinkedIn public education section' },
      { id: 'ch-10c', category: 'play_golf', text: 'Minneapolis golfer now based in Chicago — knows Medinah, Shoreacres, and Chicago golf well.', sourceSupported: true, sourceSummary: 'Blake School, Minneapolis listed on Penn roster' },
    ],
    suggestedAsks: [
      { mode: 'career_chat', ask: 'Ask about consulting vs. finance as a first job out of Penn, and how it played out for him', context: 'Brian chose consulting and made it to Partner — a strong validation of the path' },
    ],
    sourceEvidence: [
      { id: 'se-10a', url: 'https://pennathletics.com/sports/mens-golf/roster/2014-15', sourceType: 'team_roster', title: 'Penn Men\'s Golf 2014–15 Roster', snippet: 'Brian Larson — Sr. — Minneapolis, MN — Blake School', retrievedAt: '2025-05-08' },
    ],
    confidence: 'high',
    verificationStatus: 'verified',
    whyThisTieMatters: 'Brian is a McKinsey Partner — one of the most senior consulting connections in the Penn Golf network. Made it from Penn Golf to Partner in 10 years. Chicago golfer, Minnesota roots, and a strong MBA advisor.',
    howAgentFoundThis: 'Found on Penn Athletics roster pages for 2013–14 and 2014–15. LinkedIn public profile confirmed McKinsey Partner title, Penn graduation, and Chicago base.',
    isOpenToGolf: true,
    isOpenToCareerChat: true,
    isOpenToMentorship: true,
  },
]

// ─── Review Items ──────────────────────────────────────────────────────────────

export const reviewItems: ReviewItem[] = [
  {
    id: 'ri-1',
    type: 'low_confidence_match',
    title: 'Two LinkedIn profiles for Marcus Webb',
    relatedPersonName: 'Marcus Webb',
    relatedPersonId: 'np-5',
    sourceLinks: ['https://linkedin.com/in/marcus-webb-golf', 'https://linkedin.com/in/marcus-webb-nyc'],
    evidence: ['Both profiles list University of Pennsylvania', 'Only one mentions golf', 'Graduation years differ by one year'],
    confidence: 'medium',
    riskFlags: ['Common name', 'Multiple candidates', 'Conflicting graduation years'],
    suggestedAction: 'needs_more_evidence',
    createdAt: '2025-05-08T10:34:43Z',
    notes: 'Recommend a teammate confirmation before promoting either candidate.',
  },
  {
    id: 'ri-2',
    type: 'common_name_risk',
    title: '"Daniel Reyes" — 4 LinkedIn profiles in finance',
    relatedPersonName: 'Daniel Reyes',
    relatedPersonId: 'np-13',
    sourceLinks: ['https://linkedin.com/in/daniel-reyes-finance-1', 'https://linkedin.com/in/daniel-reyes-miami'],
    evidence: ['Two profiles list Penn undergrad', 'One matches class year', 'Miami, FL origin consistent with one candidate'],
    confidence: 'low',
    riskFlags: ['Very common name', 'Cannot resolve without alumni confirmation'],
    suggestedAction: 'needs_alumni_confirmation',
    createdAt: '2025-05-08T10:34:43Z',
  },
  {
    id: 'ri-3',
    type: 'missing_source',
    title: 'Samuel Park — no public profile found',
    relatedPersonName: 'Samuel Park',
    relatedPersonId: 'np-14',
    sourceLinks: ['https://pennathletics.com/sports/mens-golf/roster/2016-17'],
    evidence: ['Confirmed on Penn roster 2015–16 and 2016–17', 'No LinkedIn or employer bio found', 'Name search surfaces 40+ unrelated profiles'],
    confidence: 'unverified',
    riskFlags: ['No public profile cross-reference possible', 'May have private profile'],
    suggestedAction: 'needs_alumni_confirmation',
    createdAt: '2025-05-08T10:34:43Z',
  },
  {
    id: 'ri-4',
    type: 'possible_wrong_profile',
    title: 'Christopher Walsh — employer bio doesn\'t list Penn',
    relatedPersonName: 'Christopher Walsh',
    relatedPersonId: 'np-15',
    sourceLinks: ['https://pennathletics.com/sports/mens-golf/roster/2013-14', 'https://linkedin.com/in/christopher-walsh-pe'],
    evidence: ['Penn roster lists "C. Walsh" in 2013–14', 'LinkedIn profile is a "Christopher Walsh" in PE, class of 2014', 'No Penn mention on LinkedIn'],
    confidence: 'low',
    riskFlags: ['Name abbreviated on roster', 'No Penn mention in candidate profile', 'Could be wrong person'],
    suggestedAction: 'needs_alumni_confirmation',
    createdAt: '2025-05-08T10:34:43Z',
  },
  {
    id: 'ri-5',
    type: 'contact_path_concern',
    title: 'Jack Ambrose — contact path is "unknown"',
    relatedPersonName: 'Jack Ambrose',
    sourceLinks: ['https://pennathletics.com/sports/mens-golf/roster/2022-23'],
    evidence: ['Confirmed on Penn roster 2021–22 and 2022–23', 'No public LinkedIn, no employer bio', 'Nashville, TN origin but no Nashville profiles match'],
    confidence: 'medium',
    riskFlags: ['No verified contact path', 'Profile exists but cannot be reached'],
    suggestedAction: 'needs_alumni_confirmation',
    createdAt: '2025-05-08T10:34:43Z',
  },
  {
    id: 'ri-6',
    type: 'duplicate_person',
    title: '"J. Whitmore" and "James Whitmore" — confirmed same person',
    relatedPersonName: 'James Whitmore',
    relatedPersonId: 'np-3',
    sourceLinks: ['https://pennathletics.com/sports/mens-golf/roster/2017-18', 'https://pennathletics.com/sports/mens-golf/roster/2018-19'],
    evidence: ['Same hometown (Scottsdale, AZ) on both entries', 'Same high school (Desert Mountain HS)', 'Graduation year consistent'],
    confidence: 'high',
    riskFlags: [],
    suggestedAction: 'approve',
    createdAt: '2025-05-08T10:34:43Z',
    notes: 'Canonicalized as "James Whitmore". Safe to approve.',
  },
]

// ─── Team Stats ────────────────────────────────────────────────────────────────

export const teamStats: TeamStats = {
  alumniMapped: 84,
  verifiedProfiles: 31,
  openToGolf: 28,
  openToCareerChats: 24,
  profileCandidates: 58,
  reviewItems: 17,
  sourcePagesDrawled: 26,
  connectionHooksGenerated: 146,
}

// ─── Dashboard Sections ────────────────────────────────────────────────────────

export const dashboardSections: DashboardSection[] = [
  {
    id: 'best-ties',
    title: 'Best Ties for You',
    description: 'Strongest connections based on overlapping years, shared context, and open relationship modes.',
    alumniIds: ['alumni-1', 'alumni-3', 'alumni-8', 'alumni-4', 'alumni-10'],
  },
  {
    id: 'open-golf',
    title: 'Open to Golf Nearby',
    description: 'Alumni who indicated openness to a round and have a verified contact path.',
    alumniIds: ['alumni-1', 'alumni-2', 'alumni-4', 'alumni-6', 'alumni-9'],
  },
  {
    id: 'mentorship',
    title: 'Mentorship & Career Advice',
    description: 'Alumni with verified profiles open to career conversations and mentorship.',
    alumniIds: ['alumni-1', 'alumni-8', 'alumni-10', 'alumni-5', 'alumni-3'],
  },
  {
    id: 'founders',
    title: 'Founders & Builders',
    description: 'Alumni who have started companies or taken the founder path.',
    alumniIds: ['alumni-3', 'alumni-7'],
  },
  {
    id: 'recent-grads',
    title: 'Recently Discovered by Agent',
    description: 'Profiles added or updated in this discovery run.',
    alumniIds: ['alumni-9', 'alumni-5', 'alumni-6', 'alumni-7'],
  },
  {
    id: 'needs-review',
    title: 'Needs Review',
    description: 'Low-confidence matches that require human review before promotion.',
    alumniIds: [],
  },
]

// ─── Helpers ───────────────────────────────────────────────────────────────────

export function getAlumniById(id: string): AlumniProfile | undefined {
  return alumniProfiles.find((a) => a.id === id)
}

export function getRelationshipModeLabel(mode: string): string {
  const labels: Record<string, string> = {
    career_chat: 'Career Chat',
    play_golf: 'Play Golf',
    mentorship: 'Mentorship',
    junior_golf_family: 'Junior Golf / Family',
    city_advice: 'City Advice',
    founder_advice: 'Founder Advice',
    finance_advice: 'Finance Advice',
    grad_school_advice: 'Grad School',
    team_events: 'Team Events',
    host_dinner: 'Host / Dinner',
    program_support: 'Program Support',
    warm_intro: 'Warm Intro',
    do_not_contact: 'Do Not Contact',
  }
  return labels[mode] ?? mode
}

export function getContactPathLabel(type: string): string {
  const labels: Record<string, string> = {
    coach_intro: 'Coach Introduction',
    teammate_intro: 'Teammate Introduction',
    linkedin_public_url: 'LinkedIn',
    public_employer_bio: 'Employer Website',
    alumni_submitted: 'Alumni Submitted',
    team_directory_permissioned: 'Team Directory',
    unknown: 'Contact Path Unknown',
    do_not_contact: 'Do Not Contact',
  }
  return labels[type] ?? type
}

export function getConfidenceColor(level: string): string {
  switch (level) {
    case 'high': return 'text-emerald-600'
    case 'medium': return 'text-amber-600'
    case 'low': return 'text-orange-600'
    default: return 'text-gray-500'
  }
}

export function getIndustryIcon(industry: string): string {
  const icons: Record<string, string> = {
    'Private Equity': '📈',
    'Venture Capital': '🚀',
    'Investment Banking': '🏦',
    'Consulting': '💡',
    'Law': '⚖️',
    'Technology': '💻',
    'Medicine': '🏥',
    'Real Estate': '🏢',
    'Golf Industry': '⛳',
  }
  return icons[industry] ?? '🔗'
}
